import Head from 'next/head';
import Link from 'next/link';

import styles from '@/styles/Users.module.css';

export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const json = await res.json();

  return {
    props: {
      users: json,
    },
  };
};

export default function UsersList({ users }) {
  return (
    <>
      <Head>
        <title>Users List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="formula 1 race cars history racing" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>All Users</h1>
      {users.map((user) => (
        <Link
          key={user.id}
          className={styles.single}
          href={'/users/' + user.id}
        >
          <h3>{user.name}</h3>
        </Link>
      ))}
    </>
  );
}
