import Head from 'next/head';

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="formula 1 race cars history racing" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>About</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus
          perspiciatis nisi qui a nam cum dolores alias nulla voluptate officia!
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia corporis
          cupiditate, ab, provident nostrum ratione ipsam nisi tempora officia
          harum, illo id doloribus dolore ex assumenda non quisquam deleniti.
          Debitis!
        </p>
      </div>
    </>
  );
}
