import Head from 'next/head';
import Link from 'next/link';

import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="formula 1 race cars history racing" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.title}>
        <h1>Users</h1>
        <p className={styles.text}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Necessitatibus, aliquid.
        </p>
        <p className={styles.text}>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Harum culpa
          velit ex temporibus hic? Velit tenetur non cum deserunt placeat
          reiciendis eaque repellat officiis, ipsum possimus eum nam, totam
          dicta?
        </p>
        <Link href="/users" className={styles.btn}>
          See Users List
        </Link>
      </div>
    </>
  );
}
